name: Container Build

on:
  push:
    branches:
      - self-host
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Build Container
        uses: ./.github/actions/build-container
        with:
          version: "develop"
          push_containers: "true"
          create_release: "false"
          registry_user: ${{ secrets.DOCKER_HUB_USER }}
          registry_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          release_access_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
